package com.espe.distribuidas.pmaldito.jclient;

import com.espe.distribuidas.pmaldito.cliente.InformacionClienteRQ;
import com.espe.distribuidas.pmaldito.factura.InformacionFacturaRQ;
import com.espe.distribuidas.pmaldito.jclient.controler.ClienteSocket;
import com.espe.distribuidas.pmaldito.originador.Originador;
import com.espe.distribuidas.pmaldito.pcs.Mensaje;
import com.espe.distribuidas.pmaldito.pcs.MensajeRQ;
import com.espe.distribuidas.pmaldito.producto.InformacionProductoRQ;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class BuscarFacturaNumerofact extends javax.swing.JFrame {

    private ClienteSocket cliente;

    DefaultTableModel modelof;

    /**
     * Creates new form IngresarFactura
     */
    public BuscarFacturaNumerofact() {
        setUndecorated(true);
        setOpacity(0.95f);
        initComponents();
        modelof = new DefaultTableModel();
        modelof.addColumn("Cedula");
        modelof.addColumn("Nombre");
        modelof.addColumn("Apellido");
        modelof.addColumn("Direccion");
        modelof.addColumn("Telefono");
        modelof.addColumn("Telefono");
        modelof.addColumn("Celular");
        modelof.addColumn("Mail");
        modelof.addColumn("FechaFact");
        modelof.addColumn("Valor");
        //detalles
        modelof.addColumn("CodigoPro");
        modelof.addColumn("CodFact");
        modelof.addColumn("NombreProducto");
        modelof.addColumn("Cantidad");
        modelof.addColumn("Valor");
        tblDatosFac.setModel(modelof);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        ImageIcon imageIcon = new ImageIcon(this.getClass().getResource("/org/freedesktop/tango/22x22/actions/address-book-new.png"));
        this.setIconImage(imageIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnClientes = new javax.swing.JPanel();
        btnbusfac = new javax.swing.JButton();
        btnbusnuevo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDatosFac = new javax.swing.JTable();
        txtbusfac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnClientes.setBackground(new java.awt.Color(255, 255, 255));
        jpnClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Facturas ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 204, 0))); // NOI18N

        btnbusfac.setBackground(new java.awt.Color(51, 153, 255));
        btnbusfac.setForeground(new java.awt.Color(255, 255, 255));
        btnbusfac.setText("Buscar");
        btnbusfac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbusfacMouseClicked(evt);
            }
        });
        btnbusfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusfacActionPerformed(evt);
            }
        });

        btnbusnuevo.setBackground(new java.awt.Color(0, 255, 0));
        btnbusnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnbusnuevo.setText("Nuevo");
        btnbusnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbusnuevoMouseClicked(evt);
            }
        });
        btnbusnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusnuevoActionPerformed(evt);
            }
        });

        tblDatosFac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatosFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosFacMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDatosFac);

        javax.swing.GroupLayout jpnClientesLayout = new javax.swing.GroupLayout(jpnClientes);
        jpnClientes.setLayout(jpnClientesLayout);
        jpnClientesLayout.setHorizontalGroup(
            jpnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnClientesLayout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(txtbusfac, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnbusfac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbusnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
            .addGroup(jpnClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jpnClientesLayout.setVerticalGroup(
            jpnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbusfac)
                        .addComponent(btnbusnuevo))
                    .addComponent(txtbusfac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jpnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbusnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusnuevoActionPerformed
        // TODO add your handling code here:
        IngresarCliente ingcli = new IngresarCliente();
        ingcli.setCliente(cliente);
        ingcli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbusnuevoActionPerformed

    private void btnbusfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusfacActionPerformed
        // TODO add your handling code here:
        InformacionFacturaRQ inf = new InformacionFacturaRQ();
        inf.setValor(txtbusfac.getText());
        MensajeRQ rq = new MensajeRQ(Originador.getOriginador(Originador.CLIENTE), Mensaje.INFO_FACT);
        rq.setCuerpo(inf);
        cliente.flujo(rq.asTexto());
        Object[] arr2 = cliente.flujoRSf();
        modelof.addRow(arr2);
        //tareaCli.setText(cliente.flujoRSc());

    }//GEN-LAST:event_btnbusfacActionPerformed

    private void btnbusfacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbusfacMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnbusfacMouseClicked

    private void tblDatosFacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosFacMouseClicked
        // TODO add your handling code here:
        int x = tblDatosFac.getSelectedRow();
        /* lbNombre.setText(lbNombre.getText()+tblDatos.getValueAt(x, 2));
         lbApellido.setText(lbApellido.getText()+tblDatos.getValueAt(x, 3));
         lbRuc.setText(lbRuc.getText()+tblDatos.getValueAt(x, 1));
         lbDireccion.setText(lbDireccion.getText()+tblDatos.getValueAt(x, 4));
         lbTelefono.setText(lbTelefono.getText()+tblDatos.getValueAt(x, 5));
         lbCelular.setText(lbCelular.getText()+tblDatos.getValueAt(x, 6));
         lbCorreo.setText(lbCorreo.getText()+tblDatos.getValueAt(x, 7));*/
    }//GEN-LAST:event_tblDatosFacMouseClicked

    private void btnbusnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbusnuevoMouseClicked
        // TODO add your handling code here:
        IngresarFactura fact = new IngresarFactura();
        fact.setCliente(cliente);
        fact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbusnuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarFacturaNumerofact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarFacturaNumerofact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarFacturaNumerofact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarFacturaNumerofact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarFacturaNumerofact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbusfac;
    private javax.swing.JButton btnbusnuevo;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpnClientes;
    private javax.swing.JTable tblDatosFac;
    private javax.swing.JTextField txtbusfac;
    // End of variables declaration//GEN-END:variables

    public ClienteSocket getCliente() {
        return cliente;
    }

    public void setCliente(ClienteSocket cliente) {
        this.cliente = cliente;
    }
}
